import { Public_Sans } from 'next/font/google';
import './globals.css';

const PublicSans = Public_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'Tech commerce',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={PublicSans.className}>{children}</body>
    </html>
  );
}
